# Generated by Django 3.0.4 on 2020-05-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCountry', models.CharField(max_length=20)),
                ('descCountry', models.CharField(max_length=50)),
                ('im', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images', verbose_name='Ссылка картинки страны')),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('year_of_construction', models.IntegerField()),
                ('image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images', verbose_name='Ссылка картинки')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Country')),
            ],
        ),
    ]
