# Generated by Django 3.0.4 on 2020-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_country_sight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='descCountry',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
