# Generated by Django 3.0.4 on 2020-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200510_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='Moscow', max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Флаг'),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sight',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sight',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sight',
            name='timeOfWork',
            field=models.CharField(default='', max_length=15),
        ),
    ]
