# Generated by Django 3.0.4 on 2020-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200512_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='descCountry',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
