# Generated by Django 3.0.4 on 2020-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200513_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='im',
        ),
        migrations.AddField(
            model_name='country',
            name='im0',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 10'),
        ),
        migrations.AddField(
            model_name='country',
            name='im1',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 1'),
        ),
        migrations.AddField(
            model_name='country',
            name='im2',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 2'),
        ),
        migrations.AddField(
            model_name='country',
            name='im3',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 3'),
        ),
        migrations.AddField(
            model_name='country',
            name='im4',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 4'),
        ),
        migrations.AddField(
            model_name='country',
            name='im5',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 5'),
        ),
        migrations.AddField(
            model_name='country',
            name='im6',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 6'),
        ),
        migrations.AddField(
            model_name='country',
            name='im7',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 7'),
        ),
        migrations.AddField(
            model_name='country',
            name='im8',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 8'),
        ),
        migrations.AddField(
            model_name='country',
            name='im9',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images', verbose_name='Ссылка картинки страны 9'),
        ),
        migrations.AddField(
            model_name='country',
            name='mapCountry',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sight',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
