# Generated by Django 3.0.4 on 2020-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200513_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sight',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
