# Generated by Django 3.0.4 on 2020-05-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20200514_1316'),
        ('hello', '0007_auto_20200513_2025'),
    ]

    operations = [
    ]
