# Generated by Django 3.0.4 on 2020-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20200514_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='im0',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 10'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im1',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 1'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im2',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im3',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im4',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 4'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im5',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 5'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im6',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 6'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im7',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 7'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im8',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 8'),
        ),
        migrations.AlterField(
            model_name='country',
            name='im9',
            field=models.ImageField(blank=True, help_text='380x250px', null=True, upload_to='images/', verbose_name='Ссылка картинки страны 9'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='address',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='sight',
            name='year_of_construction',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
